baseurl = "https://mckinleyparkdevelopmentcouncil.org/"
languageCode = "en-us"
title = "McKinley Park Development Council"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "shortname"
googleAnalytics = ""
pluralizeListTitles = false


[params]
  # Sets the meta tag description
  description          = "Website of the McKinley Park Development Council"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "MPDC"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/news/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = false
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = false
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]

# Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
# due to its ease of use. Feel free to check out both and decide what you would
# prefer to use. See Staticman.yml for additional settings.
[params.staticman]
  # Sets Statiman to be active
  staticman = false
  # Sets the location for Staticman to connect to
  username  = ""
  repo      = ""
  branch    = ""

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = ""
  paragraph = ""
  about     = "The McKinley Park Development Council's mission is to collectively foster economic, cultural and social development through the connection of residents, institutions and enterprises for the benefit of the McKinley Park neighborhood of Chicago."

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/logo.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = false
    width     = ""
    alt       = "Hugo Future Imperfect"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the default language for multilanguage use.
DefaultContentLanguage = "en"

[Languages]

    [Languages.en]
        LanguageName = "English"
        title = "McKinley Park Development Council"
        description = "Powered by Hugo"
        weight = 1
        
            # Sets the menu items in the navigation bar
            # Identifier prepends a Font Awesome icon to the menu item
            # Each language has its own menu.
            [[Languages.en.menu.main]]
                name = "Home"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.en.menu.main]]
                name = "About"
                url = "/about/"
                identifier = "fa fa-id-card-o"
                weight = 2
           [[Languages.en.menu.main]]
                name = "News"
                url = "/news/"
                identifier = "fa fa-newspaper-o"
                weight = 3

            [[Languages.en.menu.main]]
                name = "Social Feed"
                url = "/social/"
                identifier = "fa fa-id-card-o"
                weight = 4

            [[Languages.en.menu.main]]
                name = "Categories"
                url = "/categories/"
                identifier = "fa fa-sitemap"
                weight = 5

            [[Languages.en.menu.main]]
                name = "Contact"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 6

    [Languages.es]
        LanguageName = "Espanol"
        title = "Consejo de Desarrollo de McKinley Park"
        description = "HTML5 UP theme, Future Imperfect avec quelques extra goodies, porté par Julio Pescador. Multilangues par StatnMap. Powered by Hugo"
        weight = 2
    
            [[Languages.es.menu.main]]
                name = "Página de inicio"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.es.menu.main]]
                name = "Noticias"
                url = "/news/"
                identifier = "fa fa-newspaper-o"
                weight = 3

     #       [[Languages.es.menu.main]]
     #           name = "Events"
     #           url = "/Events/"
     #           identifier = "fa fa-id-card-o"
     #           weight = 4

            [[Languages.es.menu.main]]
                name = "Categorías"
                url = "/categories/"
                identifier = "fa fa-sitemap"
                weight = 5

            [[Languages.es.menu.main]]
                name = "Contacto"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 6


    [Languages.zh_cn]
        LanguageName = "中文"
        title =  "McKinley Park 发展理事会"
        description = "HTML5 UP theme, Future Imperfect avec quelques extra goodies, porté par Julio Pescador. Multilangues par StatnMap. Powered by Hugo"
        weight = 3
    
            [[Languages.zh_cn.menu.main]]
                name = "家"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.zh_cn.menu.main]]
                name = "新闻"
                url = "/news/"
                identifier = "fa fa-newspaper-o"
                weight = 3

      #      [[Languages.zh_cn.menu.main]]
      #          name = "Events"
      #          url = "/Events/"
      #          identifier = "fa fa-id-card-o"
      #          weight = 4

            [[Languages.zh_cn.menu.main]]
                name = "分类"
                url = "/categories/"
                identifier = "fa fa-sitemap"
                weight = 5

            [[Languages.zh_cn.menu.main]]
                name = "联系"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 6



# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github          = "tonyatoms/MPDC-site"
#  gitlab          = ""
  stackoverflow   = "" # User Number
  bitbucket       = ""
  jsfiddle        = ""
  codepen         = ""
  # Visual Art Communities
  deviantart      = ""
  flickr          = ""
  behance         = ""
  dribbble        = ""
  # Publishing Communities
  wordpress       = ""
  medium          = ""
  # Professional/Business Oriented Communities
  linkedin        = ""
  foursquare      = ""
  xing            = ""
  slideshare      = ""
  # Social Networks
  facebook        = "McKParkDC/"
#  googleplus      = ""
  reddit          = ""
  quora           = ""
  youtube         = ""
  vimeo           = ""
  whatsapp        = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat          = ""
    qq              = "" # User ID Number
  instagram       = ""
  tumblr          = ""
  twitter         = ""
  skype           = ""
  snapchat        = ""
  pinterest       = ""
  telegram        = ""
  vine            = ""
  # Email
  email           = "mckinleyparkdevelopmentcouncil@gmail.com"
